### ISSUE TITLE
404 error is keeping trading interface from loading

### ISSUE THREAD

**Issue by andersonmmi** [OasisDEX/eth2dai#176]
Trading interface would not load.  Opened dev tools in chrome.  Screenshot and headers pasted below:

![Screen Shot 2019-03-20 at 10 33 21 AM](https://user-images.githubusercontent.com/16314437/54697522-b8d93480-4afb-11e9-99c0-08f386dfd070.png)

Request URL: https://eth2dai.com/exchange/WETH/DAI
Request Method: GET
Status Code: 404 
Remote Address: [2606:4700:30::6812:271f]:443
Referrer Policy: no-referrer-when-downgrade
access-control-allow-origin: *
age: 1688
cf-ray: 4ba8bd495ba6b5d8-MEM
content-encoding: br
content-type: text/html; charset=utf-8
date: Wed, 20 Mar 2019 15:32:32 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
status: 404
vary: Accept-Encoding
via: 1.1 varnish
x-cache: HIT
x-cache-hits: 2
x-fastly-request-id: c1d84edc5b247446badbb8541bde8d74d061bc5a
x-github-request-id: F2B4:448A:2D8AAD:3BEACC:5C925678
x-served-by: cache-atl6235-ATL
x-timer: S1553095953.873921,VS0,VE0
:authority: eth2dai.com
:method: GET
:path: /exchange/WETH/DAI
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,es;q=0.8,la;q=0.7
cache-control: max-age=0
cookie: __cfduid=d7a9c09ac3d7979cd1717031ad0ca734a1552335815
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Mobile Safari/537.36

**Comment by andersonmmi** [comment]
Ran app locally with yarn start.  Interface error persists, 404 error is not present:
![Screen Shot 2019-03-20 at 10 52 04 AM](https://user-images.githubusercontent.com/16314437/54699167-87159d00-4afe-11e9-9682-c9140b3000b1.png)

**Comment by andersonmmi** [comment]
After waiting less than 10 minutes and not giving any user input, app fails ungracefully due to unhandled error in src/blockchain/utils.ts:6:

![Screen Shot 2019-03-20 at 11 26 34 AM](https://user-images.githubusercontent.com/16314437/54701621-5ab04f80-4b03-11e9-8346-5f1ceec31662.png)

**Comment by krzkaczor** [comment]
@andersonmmi Hey! Thanks for your feedback. We will evaluate it soon and get back to you.

**Comment by peculiarity** [comment]
@andersonmmi Can you provide screenshot of what is actually loaded ( not on local environment ). Also please provide information which browser you are using , if there are any plugins activate ( such as adblock, ublock and etc. ). Which network you are connected to and everything that might be useful.

**Comment by andersonmmi** [comment]
This issue was resolved a few days after I posted this issue so I can't get any fresh screenshots.

Chrome w/metamask, no ad blockers, on main net. The app worked perfectly before and works perfectly fine now.

There must have been a microservice running on a centralized service that needed devops love 🤷‍♂️
