### ISSUE TITLE
WalletConnect Support

### ISSUE THREAD

**Issue by LaggAt** [OasisDEX/eth2dai#258]
Hi, could you look into https://walletconnect.org/ and consider implementing it?

I'd like to use my mobile wallet (Trust) from my laptop, this gives me a more user friendly ui. Trust supports WalletConnect, but it needs to be supported as Wallet in the DApp.

Thanks in advance.

**Comment by peculiarity** [comment]
Hey @LaggAt and thank you for using our products.

Apologies for the late reply. 
Our team is constantly working on improving the overall experience.  Our focus right now is mainly on giving more features to the end user. We try to support as many wallets as possible. We understand your frustration but for now we don't have WalletConnect integration in our Roadmap. That doesn't mean we won't support it though.

Feel free to ask any other questions :)!
