### ISSUE TITLE
My orders is sorted by time instead of price (as is standard) 

### ISSUE THREAD

**Issue by GriffGreen** [OasisDEX/eth2dai#79]
<img width="1188" alt="screen shot 2019-02-02 at 11 52 24 am" src="https://user-images.githubusercontent.com/14945613/52163357-1ac31380-26e1-11e9-8da6-86382e34bdcd.png">
I would love to see this sorted by price by default... even better would be if we could choose what to sort by ;-)

And btw

GREAT INTERFACE!! Super easy to use! And u love the "lock/unlock" idea.. it makes a lot more sense than "approve" 

Great work as always guys ;-)

**Comment by pimato** [comment]
I am totally agree with you.

we are going to imitate the orderbook which means:

sell orders first with highest price at the top and then
buy orders with highest price first.

Thanks for taking the time and please continue with the feedback.
We will push out the changes in the coming days.
