### ISSUE TITLE
Random blips of a higher price show up but don't make sense

### ISSUE THREAD

**Issue by GriffGreen** [OasisDEX/eth2dai#80]
<img width="1042" alt="screen shot 2019-02-04 at 3 15 27 pm" src="https://user-images.githubusercontent.com/14945613/52213622-e2156c80-288f-11e9-9ca4-c92e377f5ac4.png">
What is happening here? Orders are going thru for a much higher price then they should... and it is for a very low but weird amount... this has happened a few times now....

**Comment by krzkaczor** [comment]
@GriffGreen You can always cherry pick given order, regardless of the price.
